version: "2.3"

services:
  gobang_server:
    image: gospelslave/alphapig:v0.1.5
    entrypoint: /bin/bash run_server.sh
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8888
    volumes:
      - $PWD/run_server.sh:/workspace/run_server.sh
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "5"

  gobang_ai:
    image: gospelslave/alphapig:v0.1.5
    entrypoint: /bin/bash run_ai.sh
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/run_ai.sh:/workspace/run_ai.sh
    runtime: nvidia
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10M"
        max-file: "5"
